FROM node:22-alpine AS build
LABEL "language"="nodejs"
WORKDIR /src

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_WORKER_URL
ARG VITE_GEMINI_API_KEY
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID

RUN npm install --legacy-peer-deps
RUN npm run build

FROM zeabur/caddy-static:latest
COPY --from=build /src/dist /usr/share/caddy
EXPOSE 8080
